version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./db:/srv/db
    env_file:
      - .env
    environment:
      DATABASE_NAME: /srv/db/agent.db
    ports:
      - 8000:8000
    command:
      - make
      - migrate
      - runserver
