version: "3"
services:
  db:
    image: ankane/pgvector:latest          # PostgreSQL with pgvector
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro 

    ports:
      - "5432:5432"
    
    healthcheck:            # <- wait for the socket to be ready
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5


  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env                         # keep OPENAI_API_KEY here
    environment:
      POSTGRES_DB: ragdb
      DATABASE_URL: postgres://raguser:ragpass@db:5432/ragdb
    
    ports:
      - "8000:8000"
    command: ["make", "migrate", "runserver"]

volumes:
  pgdata:

