version: "3"
services:
  db:
    image: ankane/pgvector:latest          # PostgreSQL with pgvector
    env_file: .env

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro 

    ports:
      - "5432:5432"
  web:
    build: .
    depends_on:
      - db
    env_file: .env                         # keep OPENAI_API_KEY here
    environment:
      POSTGRES_DB: ragdb
      DATABASE_URL: postgres://raguser:ragpass@db:5432/ragdb
    
    ports:
      - "8000:8000"
    command: ["make", "migrate", "runserver"]

volumes:
  pgdata:

