# Generated by Django 5.2.5 on 2025-08-08 10:01

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rag', '0001_enable_pgvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RagChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=128)),
                ('file_name', models.CharField(max_length=512)),
                ('chunk_idx', models.IntegerField()),
                ('char_start', models.IntegerField()),
                ('char_end', models.IntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='rag_ragchun_user_id_5df46f_idx'), models.Index(fields=['file_id'], name='rag_ragchun_file_id_0b3100_idx')],
                'unique_together': {('user', 'file_id', 'chunk_idx')},
            },
        ),
    ]
