# .github/workflows/test.yml
name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ankane/pgvector:pg15   
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports: [5432:5432]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://user:pass@localhost:5432/test_db
      SECRET_KEY: test-secret
      OPENAI_API_KEY: dummy
      GOOGLE_CLIENT_ID: dummy
      GOOGLE_CLIENT_SECRET: dummy

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Enable pgvector extension
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          psql "$DATABASE_URL" -c 'CREATE EXTENSION IF NOT EXISTS vector;'

      - name: Run migrations
        run: python manage.py migrate
      
      - name: Run tests
        run: PYTHONPATH=$PWD pytest --tb=short --disable-warnings
